/*
 * @Date: 2024-06-02 21:59:59
 * @LastEditors: nickyzhang zhangxia2013105@163.com
 * @LastEditTime: 2024-06-08 22:29:47
 * @FilePath: /dedata-front/app/layout.tsx
 * @Description:
 */
import type { Metadata } from 'next';
import '@rainbow-me/rainbowkit/styles.css';
import '@/app/style/index.scss';
import NavBar from '@/app/components/NavBar';
import SideBar from '@/app/components/SideBar';
import Dashboard from '@/app/components/Dashboard';
import { Providers } from './providers';
import { AntdRegistry } from '@ant-design/nextjs-registry';

export const metadata: Metadata = {
	title: 'Dedata',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning={true}>
			<head>
				<script
					dangerouslySetInnerHTML={{
						__html: `
                        window.onresize = function () {
                            setRem();
                        };
                        function setRem() {//封装
                            var html = document.getElementsByTagName("html")[0];
                            var designSize = 1440;
                            var clientWidth = document.documentElement.clientWidth;
                            var rem = (clientWidth * 100) / designSize;
                            html.style.fontSize = rem + "px";
                        }
                        setRem();
                    `,
					}}
				/>
			</head>
			<body>
				<AntdRegistry>
					<Providers>
						<NavBar />
						<div className="flex h-[calc(100vh-0.8rem)] w-full p-[0.24rem]">
							<SideBar />
							<div className="flex-1 flex flex-col ml-[0.24rem]">
								<Dashboard />
								{children}
							</div>
						</div>
					</Providers>
				</AntdRegistry>
			</body>
		</html>
	);
}
